# Generated by Django 4.0.5 on 2022-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=64)),
                ('button1', models.CharField(max_length=64)),
                ('field2', models.CharField(max_length=64)),
                ('button2', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Button1',
        ),
        migrations.DeleteModel(
            name='Button2',
        ),
    ]
