# Generated by Django 4.0.5 on 2022-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttonapp', '0003_remove_button_button1_remove_button_button2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='field1',
            field=models.CharField(default='baza dannich', max_length=64),
        ),
    ]
